version: '3.8'

services:
  frontend:
    build:
      context: frontend/
      dockerfile: Dockerfile
    container_name: frontend-nginx
    ports:
      - "3000:80"
    depends_on:
      - backend

  backend:
    container_name: backend-fastapi
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

