version: '3.8'

services:
  frontend:
    build:
      context: frontend/
      dockerfile: Dockerfile
    container_name: frontend-nginx
    ports:
      - "80:80"

  backend:
    container_name: backend-fastapi
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

